// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrPR0WrFKHBX2fTqRc1nJIprqFNQ9NYH0',
    appId: '1:560416700623:web:ee69ab43c39e1fc5ec5fba',
    messagingSenderId: '560416700623',
    projectId: 'socialmedia-ba7a0',
    authDomain: 'socialmedia-ba7a0.firebaseapp.com',
    storageBucket: 'socialmedia-ba7a0.firebasestorage.app',
    measurementId: 'G-C5V6YWXC6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxQPTNSlpc8Mwo-mfdwtLd0P7Mbal5Qs8',
    appId: '1:560416700623:android:c1b3abe1ee982916ec5fba',
    messagingSenderId: '560416700623',
    projectId: 'socialmedia-ba7a0',
    storageBucket: 'socialmedia-ba7a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_V71FsTHoGj_-CZd5fmRt8JctctrGlas',
    appId: '1:560416700623:ios:0d790f3aa2da13c7ec5fba',
    messagingSenderId: '560416700623',
    projectId: 'socialmedia-ba7a0',
    storageBucket: 'socialmedia-ba7a0.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );
}
